### ISSUE TITLE
Eq implementation is not tail safe

### ISSUE THREAD

**Issue by CGenie** [hdgarrood/purescript-sequences#41]
Hello,

This simple code throws an error:

```purescript
import Prelude
import Data.Array as A
import Data.Sequence as Seq

s = Seq.fromFoldable $ A.range 0 10000
s == s
```

```
.psci_modules/Data.FingerTree/index.js:576
var snoc = function (dictMonoid) {
                    ^

RangeError: Maximum call stack size exceeded
    at snoc (.psci_modules/Data.FingerTree/index.js:576:21)
    at snocAll (.psci_modules/Data.FingerTree/index.js:606:17)
    at toFingerTree (.psci_modules/Data.FingerTree/index.js:615:20)
    at deepL (.psci_modules/Data.FingerTree/index.js:646:25)
    at .psci_modules/Data.FingerTree/index.js:637:28
    at .psci_modules/Data.Lazy/foreign.js:6:9
    at Module.force (.psci_modules/Data.Lazy/foreign.js:13:10)
    at .psci_modules/Data.FingerTree/index.js:658:76
    at .psci_modules/Data.FingerTree/index.js:637:112
    at .psci_modules/Data.Lazy/foreign.js:6:9
```

**Comment by CGenie** [comment]
Hm, OK, I ran this on bare `purescript-sequences` and don't get the error, I guess this is somewhere in my project, don't know why though...

**Comment by CGenie** [comment]
OK very strange, even though the source files are identical and purescript is at version 0.15.4 (I'm using code from https://github.com/hdgarrood/purescript-sequences/pull/40) I get different `Data.FingerTree/indes.js` files, especially differing at `eqFingerTree`.
